name: Hyperledger Fabric Test Network

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-fabric:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      # Step 3: Download Hyperledger Fabric binaries and Docker images
      - name: Download Hyperledger Fabric binaries
        run: |
          curl -sSL https://bit.ly/2ysbOFE | bash -s
        shell: bash
      
      # Step 4: Start Hyperledger Fabric Test Network
      - name: Start Hyperledger Fabric Test Network
        run: |
          cd fabric-samples/test-network
          ./network.sh up
          ./network.sh createChannel -c mychannel
        shell: bash
      
      # Step 5: Deploy chaincode (optional)
      - name: Deploy Chaincode
        run: |
          cd fabric-samples/test-network
          ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript
        shell: bash

